### ISSUE TITLE
No `libjpeg8` in Debian Jessie

### ISSUE THREAD

**Issue by michalrus** [psy-q/wine-unstable-debian#1]
Hey, thank you for the great work you’re doing. :+1:

In newest Debian Stable (Jessie), there’s no `libjpeg8`, see https://packages.debian.org/search?keywords=libjpeg8.

Debian is transitioning to `libjpeg-turbo`, see hhvm/packaging#96 for an example.

**Comment by psy-q** [comment]
Hey, thanks for the heads up! I'll rebuild the current version (and maybe some older ones) against `libjpeg62-turbo`. Not entirely sure how I ended up with a Jessie system that still has `libjpeg8:i386` installed, but that's another mystery.

I'm glad the packages are useful and I'm really sorry for the bad packaging :(

**Comment by psy-q** [comment]
I think I caught all of the new dependencies now. Thanks. I did warn everyone that my WINE is *horribly* packaged :)
